### PR TITLE
Dynamically assign pathGrob in .onLoad()

### LINKED ISSUE #3313: facet_wrap() and facet_grid() with a date variable is broken
The revdeps (#3303) identified that using `facet_grid()` or `facet_wrap()` with a date variable is broken. This probably affects other S3 vectors as well.

``` r
library(ggplot2)
df <- data.frame(date = as.Date("2019-01-01"), x = 1, y = 1)
p <- ggplot(df, aes(x, y)) + geom_point()
p + facet_grid(vars(date))
#> Error in scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales):
p + facet_wrap(vars(date))
#> Error in scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales):
```

The error is in `Facet(Grid|Wrap)$map_data()`, where there is a join between the layout and the panels. In one of these, `date` is a factor, and in the other, it is an S3 `Date`. This changed because of different behaviour between `join_keys()` and its previous **plyr** counterpart.

### PR DESCRIPTION
**Pull request by paleolimbot**
This is a PR to fix #3313, where packages that subclass `GeomPolygon` were giving install warnings with the new version of ggplot2 in the revdep checks (#3303).

I was hesitant to prepare this PR, because I don't understand why this works, and because I can't replicate the install warning that occurred in the revdep checks, I can't verify that this PR fixes the problem. I can verify that it doesn't cause any CMD check failures for either ggplot2 or ggspatial, which was one of the packages affected by the revdep check issue.

### CODE REVIEW

**Comment by clauswilke** [comment]
If I understand correctly what is happening, the install warnings should only occur if you're installing with R version 3.5 or earlier. Do you have an R 3.5 environment with which you could test this?

File: R/zzz.r [hunk 1]
```diff
@@ -16,9 +16,21 @@
   })
 }
 
+# Assigning pathGrob in .onLoad ensures that packages that subclass GeomPolygon
+# do not install with error `possible error in 'pathGrob(munched$x, munched$y, ':
+# unused argument (pathId = munched$group)` despite the fact that this is correct
+# usage
+pathGrob <- NULL
```
Comment (clauswilke) [inline R/zzz.r]: Just for my own understanding: Why do we need this assignment outside of `.onLoad()`?

Comment (paleolimbot) [reply R/zzz.r]: I copied what was in sf:::.onLoad() that @thomasp85 suggested we use as a reference. My guess is that it prevents the superassign from accidentally assigning in the global environment (or prevents a warning to that effect)

**Comment by clauswilke** [comment]
Thanks!
