### PR TITLE
Fix limits on `scale_colour_gradient2()` 

### LINKED ISSUE #2230: scale_color_gradient2 doesn't entirely respect limits argument
If `midpoint` is not half-way between the two values in `limits`, then the gradient scale extends beyond the limit that is closer to `midpoint` but the guide stops where `limits` specifies.  Especially in conjunction with `na.value`, this can mislead the reader.

In this plot the color scale goes below what the guide displays, and values below 2 are not indicated as `NA`.

```r
library(scales)
library(ggplot2)
library(dplyr)
ggplot(mapping = aes(x = Sepal.Length, y = Sepal.Width) ) +
  geom_point(data = iris, aes(color = Petal.Length), size = 2) +
  geom_point(data = iris %>% filter(Petal.Length < 2), size = 4, shape = 5, color = "red") +
  geom_point(data = iris %>% filter(Petal.Length > 6), size = 4, shape = 0, color = "red") +
  scale_color_gradient2(low = muted("green"), high = muted("navy"), 
                        mid = "gray80",
                        midpoint = 3, limits = c(2, 6), 
                        na.value = "orange")
```

If we change `midpoint` to `3`, then the scale truly runs from 2 to 6 and values below 2 are 
flagged.

```r
ggplot(mapping = aes(x = Sepal.Length, y = Sepal.Width) ) +
  geom_point(data = iris, aes(color = Petal.Length), size = 2) +
  geom_point(data = iris %>% filter(Petal.Length < 2), size = 4, shape = 5, color = "red") +
  geom_point(data = iris %>% filter(Petal.Length > 6), size = 4, shape = 0, color = "red") +
  scale_color_gradient2(low = muted("green"), high = muted("blue"), 
                        mid = "gray80",
                        midpoint = 4, limits = c(2, 6), 
                        na.value = "orange")
```

### PR DESCRIPTION
**Pull request by foo-bar-baz-qux**
Fixes #2230. 

Limits are now imposed before rescaling so points outside the limits don't reappear.

### CODE REVIEW

**Comment by hadley** [comment]
Could you add a little test for this please?

**Comment by foo-bar-baz-qux** [comment]
Test added, and rebased to the master branch.

File: tests/testthat/test-scale-gradient.R [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+# Limits ------------------------------------------------------------------
+
+test_that("points outside the limits are plotted as NA", {
+  p <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Petal.Length) ) +
+          geom_point() +
+          scale_color_gradient2(low = muted("green"), high = muted("navy"),
+                                mid = "gray80",
+                                midpoint = 3, limits = c(2, 6),
+                                na.value = "orange")
+  p_data <- ggplot_build(p)$data[[1]]
```
Comment (hadley) [inline tests/testthat/test-scale-gradient.R]: Can you please use `layer_data()` here

Comment (hadley) [reply tests/testthat/test-scale-gradient.R]: And I think a made up data set would make the test simpler. Maybe something like this?

```R
library(ggplot2)
df <- data.frame(x = c(0, 1, 2))

p <- ggplot(df, aes(x, 1, fill = x)) +
  geom_col() + 
  scale_fill_gradient2(limits = c(-1, 1), na.value = "orange")

layer_data(p)$fill
```

**Comment by hadley** [comment]
Are you interested in finishing this off? No problems if you don't have time; just let me know I'll get it over the finish line.

**Comment by foo-bar-baz-qux** [comment]
Yep, I can make those fixes.

**Comment by foo-bar-baz-qux** [comment]
Updated with a simpler test, thanks for the example. I've modified the `midpoint` in the example so it fails on current master build but passes on this version.

**Comment by hadley** [comment]
Thanks!
