### PR TITLE
Fix grid errors when quantiles falls outside of violin

### LINKED ISSUE #2885: geom_violin with draw_quantiles - "Error in grid.Call.graphics(C_lines, x$x, x$y, index, x$arrow) : invalid hex digit in 'color' or 'lty'"
See https://stackoverflow.com/questions/48435319/geom-violin-error-in-grid-call-graphicsc-lines-xx-xy-index-xarrow/52228544#52228544

I can't share enough data to make it reproducible, but it appears that when `draw_quantiles` has too few data to calculate the quantiles, it results in the following error:

```
Error in grid.Call.graphics(C_lines, x$x, x$y, index, x$arrow) : 
  invalid hex digit in 'color' or 'lty'
```

### PR DESCRIPTION
**Pull request by thomasp85**
Fixes #2885 

In certain instances quantiles will have `NA` coordinates and the computed aesthetics will not match the number of lines to draw, leading to grid errors

### CODE REVIEW

File: R/geom-violin.r [hunk 1]
```diff
@@ -136,12 +136,17 @@ GeomViolin <- ggproto("GeomViolin", Geom,
...
-        setdiff(names(data), c("x", "y")),
+        setdiff(names(data), c("x", "y", "group")),
         drop = FALSE
       ]
       aesthetics$alpha <- rep(1, nrow(quantiles))
       both <- cbind(quantiles, aesthetics)
-      quantile_grob <- GeomPath$draw_panel(both, ...)
+      both <- both[!is.na(both$group), , drop = FALSE]
+      quantile_grob <- if (nrow(both) == 0) {
+        zeroGrob()
```
Comment (yutannihilation) [inline R/geom-violin.r]: Do we need some warning here?

Comment (thomasp85) [reply R/geom-violin.r]: I don't think so, personally but will add it iff you feel strongly about it

Comment (yutannihilation) [reply R/geom-violin.r]: After some thinking, now I feel you are right.
