### PR TITLE
Fix for resolution - if all differences less than tolerance, return 1

### LINKED ISSUE #6562: geom_jitter fails when coordinate values have very small spread
When geom_jitter is given some data where the y coordinates are all the same, a default jitter height is chosen. But if the y coordinates differ only by a small magnitude, the selection of the jitter height seems to fail and nothing is plotted. 

Minimal working example:

``` r
library(ggplot2)

set.seed(123)
ggplot(data.frame(x = 1:50, y = 0)) +
    geom_jitter(aes(x, y))
```

``` r
set.seed(123)
ggplot(data.frame(x = 1:50, y = 1e-8 * rnorm(50))) +
    geom_jitter(aes(x, y))
#> Warning in min(d[d > tolerance]): no non-missing arguments to min; returning
#> Inf
#> Warning in stats::runif(length(x), -amount, amount): NAs produced
#> Warning: Removed 50 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

<sup>Created on 2025-07-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I would have expected both plots to be more or less the same.

### PR DESCRIPTION
**Pull request by laderast**
Fixes #6562

### CODE REVIEW

File: R/utilities-resolution.R [hunk 1]
```diff
@@ -33,5 +34,11 @@ resolution <- function(x, zero = TRUE, discrete = FALSE) {
   }
   d <- diff(sort(x))
   tolerance <- sqrt(.Machine$double.eps)
+
+  if(all(d < tolerance)){
+    return(1)
+  }
+
   min(d[d > tolerance])
+
```
Comment (thomasp85) [inline R/utilities-resolution.R:43]: Thanks for this. I think this can be solved with fewer computations by doing something `min(d[d > tolerance], 1)`

Comment (thomasp85) [reply R/utilities-resolution.R:39]: oh, I completely messed up in that suggestion. Sorry about that. 

You can revert to your old approach

Comment (laderast) [reply R/utilities-resolution.R:43]: Ah, will fix

**Comment by thomasp85** [comment]
Thanks!
