### PR TITLE
Throw error with illigal combination of space in facet_grid and aspect.ratio in theme

### LINKED ISSUE #3834: aspect ratio of plot not working with of space = "free" in facet_grid
Hi, in ggplot I want to set the aspect ratio of the plot to a certain number.
`space = "free"`in `facet_grid` does not seem to work with ` theme(aspect.ratio = 1)`. Is there a workaround for this. Also I use `coord_flip` which hinders the use of `coord_fixed.` This is what I get:

Rplot09

```r
library(ggplot2)

ggplot(mtcars, aes(hp, mpg)) +
  geom_point(aes()) +
  coord_flip()+
  theme(aspect.ratio = 1)+
  facet_grid(vars(cyl), space = "free")
```

### PR DESCRIPTION
**Pull request by thomasp85**
Fix #3834 

This PR adds a check for when aspect ratio has been set by the theme and free space is requested in facet_grid and throws an error

### CODE REVIEW

File: R/facet-grid-.r [hunk 1]
```diff
@@ -309,6 +309,9 @@ FacetGrid <- ggproto("FacetGrid", Facet,
     strips <- render_strips(col_vars, row_vars, params$labeller, theme)
 
     aspect_ratio <- theme$aspect.ratio
+    if (!is.null(aspect_ratio) && (params$space$x || params$space$y)) {
```
Comment (yutannihilation) [inline R/facet-grid-.r:312]:
```suggestion
    if (!is.null(aspect_ratio) && (params$space_free$x || params$space_free$y)) {
```

**Review by yutannihilation — APPROVED** [review]
Looks good other than this partial matching

File: R/facet-grid-.r (hunk 1 above)
Comment (thomasp85) [reply R/facet-grid-.r:312]: Thanks!
