### PR TITLE
Fix geom_rug + coord_flip

### LINKED ISSUE #2987: geom_rug and coord_flip do not work together
``` r
library(ggplot2)

df <- data.frame(x=1:10, y=(1:10)^3)
g <- ggplot(df, aes(x, y)) + geom_point() + geom_rug(sides='l')

# Normal plot
g
```

``` r

# coord_flip does not flip the rugs
g + coord_flip()
```

<sup>Created on 2018-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Problem**

The location of the rugs is contained in the `sides` parameter of `geom_rug`. The parameters of a geom are not passed to the coordinate system and so it cannot manipulate them.

### PR DESCRIPTION
**Pull request by has2k1**
The rugs in `geom_rug` are drawn along an axis depending the
`sides` parameter. Since the coordinate system does not alter
the `geom` parameters, the `geom` has to alter any parameters
that determine where the geoms are plotted.

fixes #2987 

----

``` r
library(ggplot2)

df <- data.frame(x = 1:10, y = (1:10)^3)
g <- ggplot(df, aes(x, y)) + geom_point() + geom_rug(sides = 'l')

# Normal plot
g
```

``` r

# The rugs are flipped
g + coord_flip()
```

<sup>Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

File: R/geom-rug.r [hunk 1]
```diff
@@ -66,6 +66,10 @@ GeomRug <- ggproto("GeomRug", Geom,
     rugs <- list()
     data <- coord$transform(data, panel_params)
 
+    if (inherits(coord, 'CoordFlip')) {
```
Comment (clauswilke) [inline R/geom-rug.r]: I wish we wouldn't test for capabilities by testing for inheritance, but this is how it's done for `CoordFlip` all over the ggplot2 code base, so I guess it's fine.

File: R/geom-rug.r [hunk 2]
```diff
@@ -66,6 +66,10 @@ GeomRug <- ggproto("GeomRug", Geom,
...
+      sides <- chartr('tblr', 'rlbt', sides)
```
Comment (clauswilke) [inline R/geom-rug.r]: Would you mind adding a comment to this line explaining what's happening?

File: R/geom-rug.r (hunk 1 above)
Comment (has2k1) [reply R/geom-rug.r]: The first instinct was to use `is()`, but it was not used anywhere in the coord base.

File: R/geom-rug.r (hunk 2 above)
Comment (has2k1) [reply R/geom-rug.r]: I have added a comment to the block.

File: R/geom-rug.r (hunk 1 above)
Comment (clauswilke) [reply R/geom-rug.r]: What I meant was other coord features are queried by asking the coord, e.g. `coord$is_free()`. So it would probably make sense to introduce `coord$is_flip()`. But that's for a different PR.

**Comment by clauswilke** [comment]
@hadley This looks good to me. Any concerns from you?
