### PR TITLE
Handle NA gracefully in geom_sf

### LINKED ISSUE #3536: Regression: geom_sf() is now too aggressive in removing rows
I just encountered this problem where `geom_sf()` removes polygons that are plotted without outline. This is a regression in current ggplot2 master. I assume it's due to #3491.

cc @yutannihilation

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0

# make outline of the world in robinson coordinates
lats <- c(90:-90, -90:90, 90)
longs <- c(rep(c(180, -180), each = 181), 180)

robin_outline <- 
  list(cbind(longs, lats)) %>%
  st_polygon() %>%
  st_sfc(crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") %>% 
  st_sf() %>%
  st_transform(crs = "+proj=robin +lat_0=0 +lon_0=0 +x0=0 +y0=0")

# plot with line
ggplot(robin_outline) +
  geom_sf(fill = "#56B4E950", color = "black")
```

``` r

# plot without line
ggplot(robin_outline) +
  geom_sf(fill = "#56B4E950", color = NA)
#> Warning: Removed 1 rows containing missing values (geom_sf).
```

<sup>Created on 2019-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by thomasp85**
Fixes #3536

This is an alternative implementation to the fix in #3537 that respects the different geometry types interpretation of NA. As the problem of NA's is unique to the vectorised constructors there is no need to handle geometrycollections in any special way as they will always be treated as scalars and grid accepts a single NA in `gpar()`

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3

pt <- st_point(1:2)

outer <- matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)
pl <- st_polygon(list(outer))

# point is shown
sf1 <- st_sf(geometry = st_sfc(pl, pt))
ggplot(sf1) + geom_sf()
```

``` r

# point is still shown as expected
sf2 <- st_sf(geometry = st_sfc(st_geometrycollection(list(pl, pt))))
ggplot(sf2) + geom_sf()
```

``` r

# NA is handled fine for collections
ggplot(sf2) + geom_sf(colour = NA)
```

``` r

# as well as for vectorised geometries
sf3 <- st_sf(geometry = st_sfc(pt, st_point(3:4)), one_na = c(1, NA))
ggplot(sf3) + geom_sf(aes(size = one_na))
```

<sup>Created on 2019-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

File: R/utilities.r [hunk 1]
```diff
@@ -107,6 +100,10 @@ remove_missing <- function(df, na.rm = FALSE, vars = names(df), name = "",
 
   df
 }
+detect_missing <- function(df, vars, finite = FALSE) {
+  vars <- intersect(vars, names(df))
+  !cases(df[, vars, drop = FALSE], if (finite) is_finite else is_complete)
```
Comment (clauswilke) [inline R/utilities.r]: Is this line correct? Where does `is_complete` come from?

File: NEWS.md [hunk 2]
```diff
@@ -1,5 +1,7 @@
 # ggplot2 (development version)
 
+* `geom_sf()` now removes rows can't be plotted due to `NA` aesthetics (#3546, @thomasp85)
```
Comment (clauswilke) [inline NEWS.md]: "removes rows *that* can't be plotted"

**Comment by clauswilke** [comment]
Could you also verify that the example from #3483 still works?

File: R/utilities.r (hunk 1 above)
Comment (thomasp85) [reply R/utilities.r]: It's a function defined in `utilitites.r`. `detect_missing()` is more or less lifted from `remove_missing()` so that `sf_grobs()` can use the same logic as `handle_na()`

**Comment by thomasp85** [comment]
>Could you link to the original bug report in one of the commit messages: #3536
It is linked at the top of the PR. Why would you want it in a commit message (that will get squashed away during merge)?

>Could you also verify that the example from #3483 still works?
I've done that already (but forgot to mention). Do you want a repress of it?

File: R/geom-sf.R [hunk 3]
```diff
@@ -133,16 +131,30 @@ default_aesthetics <- function(type) {
...
+    is_collection <- is_collection[!remove]
+  }
   defaults <- list(
     GeomPoint$default_aes,
     GeomLine$default_aes,
     modify_list(GeomPolygon$default_aes, list(fill = "grey90", colour = "grey35"))
   )
+  defaults[[4]] <- modify_list(
+    defaults[[3]],
+    rename(GeomPoint$default_aes, c("size" = "point_size", "fill" = "point_fill"))
```
Comment (yutannihilation) [inline R/geom-sf.R]:
```suggestion
    rename(GeomPoint$default_aes, c(size = "point_size", fill = "point_fill"))
```

**Comment by yutannihilation** [comment]
One minor problem of this approach to move the process to outside of `handle_na()` is that `na.rm` no longer controls whether or not to warn, we need to choose always be quiet or always warn. I think the latter should be slightly better, but am not fully sure what should be done here.

```
> test_check("ggplot2")

── 1. Failure: geom_sf() removes rows containing missing aes (@test-geom-sf.R#85

`expect_identical(...)` did not produce any warnings.

── 2. Failure: geom_sf() removes rows containing missing aes (@test-geom-sf.R#89

`expect_identical(...)` did not produce any warnings.

── 3. Failure: geom_sf() removes rows containing missing aes (@test-geom-sf.R#94

`expect_identical(...)` did not produce any warnings.
```
(https://travis-ci.org/tidyverse/ggplot2/jobs/591938837#L1219-L1227)
