### PR TITLE
fix "inward" and "outward" hjust and vjust in geom_text() with angle > 45

### LINKED ISSUE #4169: hjust = "outward" not working for some angles
In the following code, the label "Annotation0" is not adjusted "outwards", while the other two are.

```r
library(ggplot2)
print(ggplot(data.frame(x = c(0, 1, 2))) +
  geom_text(aes(
    x = x,
    y = 1,
    label = paste0("Annotation", x),
    angle = x * 60 - 90, 
    hjust = "outward"
    )) + 
  coord_polar() +
  scale_x_continuous(limits = c(0, 3))
)
```
image

### PR DESCRIPTION
**Pull request by aphalo**
Fix #4169

In `geom_text()` when `abs(angle) > 45` justification applied based on the orientation of the text labels is done along the x axis for `vjust` and along the y axis for `hjust`. For `"outward"` and `"inward"` to behave correctly, the value tested against 0.5 needs to change from x to y and vice versa based on the value of `angle` in each row in `data`. 

This pull request adds code to `draw_panel` in `GeomText`  to handle `"outward"` and `"inward"` as special cases.

Reprex with 'ggplot2' 3.3.3

``` r
library(ggplot2)

my.cars <- mtcars[c(TRUE, FALSE, FALSE, FALSE), ]

p <- ggplot(my.cars, aes(wt, mpg, label = rownames(my.cars))) +
  geom_point(colour = "red")

p + geom_text(hjust = "outward")
```

``` r
p + geom_text(hjust = "outward", angle = 30)
```

``` r
p + geom_text(hjust = "outward", angle = 70)
```

<sup>Created on 2021-04-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_Finland.1252        
#>  ctype    English_Finland.1252        
#>  tz       Europe/Helsinki             
#>  date     2021-04-24                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.0.3)
#>  cli           2.4.0   2021-04-05 [1] CRAN (R 4.0.4)
#>  colorspace    2.0-0   2020-11-11 [1] CRAN (R 4.0.3)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.3)
#>  curl          4.3     2019-12-02 [1] CRAN (R 4.0.0)
#>  DBI           1.1.1   2021-01-15 [1] CRAN (R 4.0.3)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
#>  dplyr         1.0.5   2021-03-05 [1] CRAN (R 4.0.4)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.3)
#>  farver        2.1.0   2021-02-28 [1] CRAN (R 4.0.4)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.3)
#>  ggplot2     * 3.3.3   2020-12-30 [1] CRAN (R 4.0.5)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.4)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.3)
#>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
#>  knitr         1.32    2021-04-14 [1] CRAN (R 4.0.4)
#>  labeling      0.4.2   2020-10-20 [1] CRAN (R 4.0.3)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.4)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
#>  mime          0.10    2021-02-13 [1] CRAN (R 4.0.3)
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.0)
#>  pillar        1.6.0   2021-04-13 [1] CRAN (R 4.0.5)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
#>  reprex        2.0.0   2021-04-02 [1] CRAN (R 4.0.4)
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
#>  rmarkdown     2.7     2021-02-19 [1] CRAN (R 4.0.4)
#>  scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  styler        1.4.1   2021-03-30 [1] CRAN (R 4.0.4)
#>  tibble        3.1.1   2021-04-18 [1] CRAN (R 4.0.4)
#>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.4)
#>  vctrs         0.3.7   2021-03-29 [1] CRAN (R 4.0.4)
#>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.4)
#>  xfun          0.22    2021-03-11 [1] CRAN (R 4.0.4)
#>  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Users/Aphalo/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.5/library
```

</details>

Similar reprex, adding one example, after applying this pull request to current 'master' branch from GitHub.

``` r
library(ggplot2)

my.cars <- mtcars[c(TRUE, FALSE, FALSE, FALSE), ]

p <- ggplot(my.cars, aes(wt, mpg, label = rownames(my.cars))) +
  geom_point(colour = "red")

p + geom_text(hjust = "outward")
```

``` r
p + geom_text(hjust = "outward", angle = 30)
```

``` r
p + geom_text(hjust = "outward", angle = 70)
```

``` r
p + geom_text(hjust = "outward", angle = 90)
```

<sup>Created on 2021-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_Finland.1252        
#>  ctype    English_Finland.1252        
#>  tz       Europe/Helsinki             
#>  date     2021-04-25                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.2.1      2020-12-09 [1] CRAN (R 4.0.3)
#>  cli           2.4.0      2021-04-05 [1] CRAN (R 4.0.4)
#>  colorspace    2.0-0      2020-11-11 [1] CRAN (R 4.0.3)
#>  crayon        1.4.1      2021-02-08 [1] CRAN (R 4.0.3)
#>  curl          4.3        2019-12-02 [1] CRAN (R 4.0.0)
#>  DBI           1.1.1      2021-01-15 [1] CRAN (R 4.0.3)
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.0.3)
#>  dplyr         1.0.5      2021-03-05 [1] CRAN (R 4.0.4)
#>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.2      2021-01-15 [1] CRAN (R 4.0.3)
#>  farver        2.1.0      2021-02-28 [1] CRAN (R 4.0.4)
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)
#>  generics      0.1.0      2020-10-31 [1] CRAN (R 4.0.3)
#>  ggplot2     * 3.3.3.9000 2021-04-24 [1] local         
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)
#>  gtable        0.3.0      2019-03-25 [1] CRAN (R 4.0.0)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.0.4)
#>  htmltools     0.5.1.1    2021-01-22 [1] CRAN (R 4.0.3)
#>  httr          1.4.2      2020-07-20 [1] CRAN (R 4.0.2)
#>  knitr         1.32       2021-04-14 [1] CRAN (R 4.0.4)
#>  labeling      0.4.2      2020-10-20 [1] CRAN (R 4.0.3)
#>  lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.0.4)
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.0.3)
#>  mime          0.10       2021-02-13 [1] CRAN (R 4.0.3)
#>  munsell       0.5.0      2018-06-12 [1] CRAN (R 4.0.0)
#>  pillar        1.6.0      2021-04-13 [1] CRAN (R 4.0.5)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.3)
#>  reprex        2.0.0      2021-04-02 [1] CRAN (R 4.0.4)
#>  rlang         0.4.10     2020-12-30 [1] CRAN (R 4.0.3)
#>  rmarkdown     2.7        2021-02-19 [1] CRAN (R 4.0.4)
#>  scales        1.1.1      2020-05-11 [1] CRAN (R 4.0.0)
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)
#>  styler        1.4.1      2021-03-30 [1] CRAN (R 4.0.4)
#>  tibble        3.1.1      2021-04-18 [1] CRAN (R 4.0.4)
#>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.0)
#>  utf8          1.2.1      2021-03-12 [1] CRAN (R 4.0.4)
#>  vctrs         0.3.7      2021-03-29 [1] CRAN (R 4.0.4)
#>  withr         2.4.2      2021-04-18 [1] CRAN (R 4.0.4)
#>  xfun          0.22       2021-03-11 [1] CRAN (R 4.0.4)
#>  xml2          1.3.2      2020-04-23 [1] CRAN (R 4.0.0)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Users/Aphalo/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.5/library
```

</details>

This may change the rendering of some old plots, but the old behavior is in my view wrong, and this pull request a bug fix.

### CODE REVIEW

**Review by thomasp85 — CHANGES_REQUESTED** [review]
Thanks! I think I would prefer if all the angle logic was contained in `compute_just()` rather than getting repeated...

so, `compute_just()` would be:

```r
compute_just <- function(just, x, y, angle) {
  ...
}
```

**Comment by aphalo** [comment]
@thomasp85 I think angle is relevant only to `geom_text()` but `compute_just()` is also used elsewhere... so one would need to have NULL as default for `angle` not to break the use of `compute_just()` elsewhere. I guess what is best depends on how widespread support for `angle` will be in the future. In principle support could be expanded to other geoms as grobs can be rotated. While I write this I convinced myself that you are correct. I will revise the code during the weekend.

**Comment by aphalo** [comment]
@thomasp85 When revising the code at first and also in the original pull request I failed to realize that angle is set to zero in default_aes. Once I realized this I could simplify the code and easily implement the change you suggested. I also added a couple of test cases. At one point I edited geom_label() but I later reverted all these changes.

**Comment by thomasp85** [comment]
Thanks! Can I get you to add a bulletpoint to the NEWS file?

**Comment by aphalo** [comment]
@thomasp85 I added the bullet point but this created a conflict. Anyway you had linked to #4169 so I tested against the reprex there once I noticed this earlier issue and I am afraid the problem is not solved by my pull request yet. I will have a look.

**Comment by thomasp85** [comment]
Don't worry about the conflict - that is common with the news file and can be fixed just before merging. Thanks for looking into the reprex👍

**Comment by aphalo** [comment]
I updated the code to handle correctly angles in -360...+360. To handle angles outside this range I could add `angle <- angle %% 360` but this feels like costly overkill. What do you think? Now also #4169 is resolved. The reprex below shows several additional examples that were missing in my original reprex above and also the reprex from #4169. I also resolved the NEWS.md conflict.

I think that now this is ready. I renamed some variables to enhance readability of the code.

``` r
library(ggplot2)

my.cars <- mtcars[c(TRUE, FALSE, FALSE, FALSE), ]

p <- ggplot(my.cars, aes(wt, mpg, label = rownames(my.cars))) +
  geom_point(colour = "red")

p + geom_text(hjust = "outward")
```



``` r
p + geom_text(hjust = "outward", angle = 30)
```



``` r
p + geom_text(hjust = "outward", angle = 70)
```



``` r
p + geom_text(hjust = "outward", angle = 90)
```



``` r
p + geom_text(hjust = "outward", angle = 150)
```



``` r
p + geom_text(hjust = "outward", angle = 220)
```



``` r
p + geom_text(hjust = "outward", angle = 320)
```



``` r
p + geom_text(hjust = "outward", angle = -30)
```



``` r
p + geom_text(hjust = "outward", angle = -70)
```



``` r
p + geom_text(hjust = "outward", angle = -90)
```



``` r
p + geom_text(hjust = "outward", angle = -150)
```



``` r
p + geom_text(hjust = "outward", angle = -220)
```



``` r
p + geom_text(hjust = "outward", angle = -320)
```



``` r
# Issue #4169

print(ggplot(data.frame(x = c(0, 1, 2))) +
        geom_text(aes(
          x = x,
          y = 1,
          label = paste0("Annotation", x),
          angle = x * 60 - 90, 
          hjust = "outward"
        )) + 
        coord_polar() +
        scale_x_continuous(limits = c(0, 3))
)
```



<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by thomasp85** [comment]
I think you should add `angle <- angle %% 360` — a quick test shows that for 1mil angles. it would take around 15ms on my computer which is negligible to plotting 1mil labels

**Comment by aphalo** [comment]
@thomasp85 In addition to your request I added three new test cases. I think they will not be a burden as they directly test `compute_just()`.

File: R/geom-label.R [hunk 1]
```diff
@@ -67,6 +67,7 @@ GeomLabel <- ggproto("GeomLabel", Geom,
     }
 
     data <- coord$transform(data, panel_params)
+
```
Comment (thomasp85) [inline R/geom-label.R:70]: Can you avoid touching files and functions that you don't change

File: R/geom-text.r [hunk 2]
```diff
@@ -234,14 +235,34 @@ GeomText <- ggproto("GeomText", Geom,
...
+    just[inward] <- c("left", "middle", "right")[just_dir(ab[inward])]
+    outward <-
+      (just == "outward" & !just_swap) | (just == "inward" & just_swap)
+    just[outward] <- c("right", "middle", "left")[just_dir(ab[outward])]
+
+  }
 
   unname(c(left = 0, center = 0.5, right = 1,
-    bottom = 0, middle = 0.5, top = 1)[just])
+           bottom = 0, middle = 0.5, top = 1)[just])
```
Comment (thomasp85) [inline R/geom-text.r:265]: Same as other comment - don't touch code format in unrelated code

**Review by thomasp85 — CHANGES_REQUESTED** [review]
Almost there - sorry for not catching these two small issues earlier

File: R/geom-label.R (hunk 1 above)
Comment (aphalo) [reply R/geom-label.R:70]: Sorry, this was an accident. Left from from en edit that I reverted during development. Will fix in a minute.

File: R/geom-text.r (hunk 2 above)
Comment (aphalo) [reply R/geom-text.r:265]: Will also fix.

**Review by thomasp85 — APPROVED** [review]
Thank you for all your work on this!

**Comment by aphalo** [comment]
Thank you for helping me get the pull request in good shape!
