### PR TITLE
fixes issue #3016 by adding % info for file name and removes extra be

### LINKED ISSUE #3016: Invalid filename error with ggsave after saving in a folder with a percentage sign (%)
When using `ggsave`, I get an invalid filename error on Windows 7 when I include a percentage in the filename.

```r
library(ggplot2)

# create a temporary folder
folder <- tempdir()

# create a plot
p <- ggplot(mtcars, aes(x = mpg, y = cyl)) +
  geom_point()

# save the plot in the temporary folder
ggsave(file.path(folder, "test.png"), p)
#> Saving 7 x 5 in image

# create folder with percentage (%) in the name
folder_perc <- file.path(folder, "perc%")
dir.create(folder_perc)

# show error in this new subfolder
ggsave(file.path(folder_perc, "test.png"), p)
#> Saving 7 x 5 in image
#> Error in grDevices::png(..., res = dpi, units = "in"): invalid 'filename'
```

### PR DESCRIPTION
**Pull request by connorlewis**
Added note about including percentage sign in the filename. Also removed extra "be" from devices. 
Fixes #3016

### CODE REVIEW

File: R/save.r [hunk 1]
```diff
@@ -5,9 +5,17 @@
 #' graphics device. It also guesses the type of graphics device from the
 #' extension.
 #'
+#' Note: Filenames with page numbers can be generated by including a C
+#' integer format expression, such as `%03d` (as in the default file name
+#' for most R graphics devices, see e.g. [png()].
```
Comment (clauswilke) [inline R/save.r]: I think there's a closing parenthesis missing.

File: R/save.r [hunk 2]
```diff
@@ -5,9 +5,17 @@
...
+#' Thus, `filename = "figure%03d.png"` will produce successive filenames
+#' `figure001.png`, `figure002.png`, `figure003.png`, etc. To write a filename
+#' containing the `%` sign, use `%%`. For example, `filename = "figure-100%%.png"`
+#' will produce the filename `figure-100%.png`.
+#'
 #' @param filename File name to create on disk.
 #' @param plot Plot to save, defaults to last plot displayed.
-#' @param device Device to use. Can be either be a device function
+#' @param device Device to use. Can ther be a device function
```
Comment (clauswilke) [inline R/save.r]: You lost the "ei".

**Comment by clauswilke** [comment]
Thanks!
