### PR TITLE
Check for dropped aesthetics

### LINKED ISSUE #3250: Unexpected failure of density plot without any error or warning
I encountered the following example when teaching density plots. If a discrete variable is encoded as numerical (e.g., 0/1), and that variable is mapped onto `fill`, the variable values get replaced with `NA` and no fill is applied/no grouping is calculated. Importantly, this happens without any kind of error or warning message, so students get no indication of what they have done wrong, or that something went wrong at all.

It's not immediately clear to me whether and how we can catch this situation, but it would be good if we could. Reprex follows.

``` r
library(ggplot2)

# desired plot
p1 <- ggplot(mtcars, aes(mpg, fill = factor(am))) + geom_density(alpha = 0.4)
p1
```

``` r

# broken plot because factor() is missing
p2 <- ggplot(mtcars, aes(mpg, fill = am)) + geom_density(alpha = 0.4)
p2
```

``` r

# fill has been set to NA
head(layer_data(p2))
#>            y PANEL        x    density    scaled  ndensity     count  n
#> 1 0.01922476     1 10.40000 0.01922476 0.2829075 0.2829075 0.6151923 32
#> 2 0.01951519     1 10.44599 0.01951519 0.2871815 0.2871815 0.6244861 32
#> 3 0.01980689     1 10.49198 0.01980689 0.2914740 0.2914740 0.6338204 32
#> 4 0.02010390     1 10.53796 0.02010390 0.2958448 0.2958448 0.6433248 32
#> 5 0.02040182     1 10.58395 0.02040182 0.3002289 0.3002289 0.6528583 32
#> 6 0.02070509     1 10.62994 0.02070509 0.3046918 0.3046918 0.6625630 32
#>   group ymin       ymax fill weight colour alpha size linetype
#> 1    -1    0 0.01922476   NA      1  black   0.4  0.5        1
#> 2    -1    0 0.01951519   NA      1  black   0.4  0.5        1
#> 3    -1    0 0.01980689   NA      1  black   0.4  0.5        1
#> 4    -1    0 0.02010390   NA      1  black   0.4  0.5        1
#> 5    -1    0 0.02040182   NA      1  black   0.4  0.5        1
#> 6    -1    0 0.02070509   NA      1  black   0.4  0.5        1
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by clauswilke**
Check for dropped aesthetics and issue a warning if aesthetics are dropped that shouldn't be. Fixes #3250.

As a consequence of this change, stats now need to advertise which aesthetics they are dropping, via the new `dropped_aes` field. If they don't, unit tests may fail because code now generates warnings that previously ran quietly.

Example of the new feature:

``` r
library(tidyverse)

ggplot(mtcars, aes(mpg, fill = am)) + geom_density(alpha = 0.4)
#> Warning: The following aesthetics were dropped during statistical transformation: fill
#> ℹ This can happen when ggplot fails to infer the correct grouping structure in
#>   the data.
#> ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
#>   variable into a factor?
```

``` r
ggplot(mtcars, aes(mpg, fill = am, group = am)) + geom_density(alpha = 0.4)
```

<sup>Created on 2022-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

File: R/stat-density-2d.r [hunk 1]
```diff
@@ -149,6 +153,8 @@ StatDensity2d <- ggproto("StatDensity2d", Stat,
     } else { # lines is the default
       contour_stat <- StatContour
```
Comment (thomasp85) [inline R/stat-density-2d.r:154]: I think you need to make a new object since you are modifying a field of it below and it will affect everything inheriting from `StatContour` afterwards
```suggestion
      contour_stat <- ggproto(NULL, StatContour)
```

File: R/stat-.r [hunk 2]
```diff
@@ -122,7 +127,20 @@ Stat <- ggproto("Stat",
       )
     }, stats, groups, SIMPLIFY = FALSE)
 
-    rbind_dfs(stats)
+    data_new <- rbind_dfs(stats)
```
Comment (thomasp85) [inline R/stat-.r:130]: `rbind_dfs()` will be removed in favour of `vec_rbind()` soon, just to remember depending on whether this gets merged before or after

**Review by thomasp85 — CHANGES_REQUESTED** [review]
Generally looks good - should we update the docs for the affected stats to say that these aesthetics are dropped? Seems like a nice thing to do

File: R/stat-density-2d.r (hunk 1 above)
Comment (clauswilke) [reply R/stat-density-2d.r:154]: Yes, correct. It didn't matter in the past but it matters now. I'll fix it.

**Comment by clauswilke** [comment]
Let me think about documenting the dropped aesthetics. In some cases it's just a temporary variable that gets dropped, so documenting that is not so useful. In other cases (e.g. `stat_density_2d()`) one of the input variables gets dropped, so documenting that makes sense.

**Comment by thomasp85** [comment]
yeah - "thankfully" the stats aes documentation is not automatic so it is just a matter of cherry picking where to add it to the docs

File: R/stat-.r (hunk 2 above)
Comment (clauswilke) [reply R/stat-.r:130]: I just saw your PR. I think I'll wait until you've merged it and then apply the update in my code.

**Comment by thomasp85** [comment]
@clauswilke is it possible to get the docs updated soon? I plan to start the release process soonish to give the revdep maintainers the summer to fix potential issues

**Comment by clauswilke** [comment]
@thomasp85 I think I can do it today. I was waiting for you to merge the vctrs PR, but that has happened, correct?

**Comment by thomasp85** [comment]
Ah, sorry -- I missed that. Yes, vctrs has been merged in

**Comment by clauswilke** [comment]
@thomasp85 I think I've addressed everything. I documented the stats where it seemed appropriate. In particular, I didn't document `stat_boxplot()` because I think it'd be more confusing if I did than if I didn't.

**Review by thomasp85 — APPROVED** [review]
lgtm
