### PR TITLE
Fix warning in geom_violin with draw_quantiles

### LINKED ISSUE #4455: collapsing to unique 'x' values in geom_violin with draw_quantiles
I receive the warning 
```
In regularize.values(x, y, ties, missing(ties), na.rm = na.rm) :
  collapsing to unique 'x' values
```
with this code:
```r
df <- data.frame(x = 1, y = c(0, 0.25, 0.5, 0.75, 5))
ggplot2::ggplot(df, ggplot2::aes(x = x, y = y)) +
    ggplot2::geom_violin(draw_quantiles = c(0.5))
```
The warning does not appear with
```r
df <- data.frame(x = 1, y = c(0, 0.25, 0.5, 0.75, 4))
```
so it is not a problem of the structure (including any potential duplicates) of the data.

```
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] glue_1.4.2

loaded via a namespace (and not attached):
 [1] fansi_0.4.2      digest_0.6.27    assertthat_0.2.1 dplyr_1.0.5
 [5] utf8_1.1.4       crayon_1.4.1     grid_4.0.5       R6_2.5.0
 [9] DBI_1.1.1        lifecycle_1.0.0  gtable_0.3.0     magrittr_2.0.1
[13] scales_1.1.1     ggplot2_3.3.3    pillar_1.5.1     rlang_0.4.10
[17] farver_2.1.0     generics_0.1.0   vctrs_0.3.6      ellipsis_0.3.1
[21] labeling_0.4.2   purrr_0.3.4      munsell_0.5.0    compiler_4.0.5
[25] pkgconfig_2.0.3  colorspace_2.0-0 tidyselect_1.1.0 tibble_3.1.0
```

### PR DESCRIPTION
**Pull request by bersbersbers**
Fix "collapsing to unique 'x' values" warnings. Closes #4455

A test will follow in a later commit.

### CODE REVIEW

**Comment by thomasp85** [comment]
Hi @bersbersbers - can I get you to merge in the main branch to kick off CI?

File: tests/testthat/test-geom-violin.R [hunk 1]
```diff
@@ -90,6 +98,10 @@ test_that("geom_violin draws correctly", {
   expect_doppelganger("quantiles",
     ggplot(dat, aes(x=x, y=y)) + geom_violin(draw_quantiles=c(0.25,0.5,0.75))
   )
+  dat_outlier <- data.frame(x = 1, y = c(0, 0.25, 0.5, 0.75, 5))
```
Comment (hadley) [inline tests/testthat/test-geom-violin.R:101]: Why do we need a visual test here?

File: tests/testthat/test-geom-violin.R [hunk 2]
```diff
@@ -46,6 +46,14 @@ test_that("quantiles do not fail on zero-range data", {
   expect_equal(length(layer_grob(p)), 1)
 })
 
+test_that("quantiles do not issue warning", {
+  df <- data.frame(x = 1, y = c(0, 0.25, 0.5, 0.75, 5))
+
+  p <- ggplot(df, aes(x = x, y = y)) +
+    geom_violin(draw_quantiles = c(0.5))
+
+  expect_warning(plot(p), regexp = NA)
```
Comment (hadley) [inline tests/testthat/test-geom-violin.R:55]: Can you please either use `expect_snapshot_warning()` here, or include a `regexp` to confirm that you're matching the expected warning?

Comment (bersbersbers) [reply tests/testthat/test-geom-violin.R:55]: `expect_warning(..., regexp = NA)` asserts that there should be no warnings, so the lack of a regexp is intentional (the point of this PR is to remove a warning), compare https://stackoverflow.com/a/33638939. Do you see a way of achieving that with `expect_snapshot_warning()`?

File: tests/testthat/test-geom-violin.R (hunk 1 above)
Comment (bersbersbers) [reply tests/testthat/test-geom-violin.R:101]: Good question - maybe we don't. The change in 
https://github.com/tidyverse/ggplot2/pull/4654/files/09b4df9ed1b61d1071c00b1d5a886f72d5a4e57d#diff-6ac793ea0483ba5c6cd55aa4b47e2a9fca57dc1d867fb0ee8851058dfae407d5R200
does not affect any of the existing visual tests, so I thought it might make sense to add a visual test that is affected by the fix and, in fact, make sure the (originally invisible) quantile line stays invisible.

File: tests/testthat/test-geom-violin.R (hunk 2 above)
Comment (hadley) [reply tests/testthat/test-geom-violin.R:55]: Oh sorry, I missed that.

**Review by hadley — COMMENTED** [review]
Can you please also add a bullet to the top of `NEWS.md`? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

File: tests/testthat/test-geom-violin.R (hunk 1 above)
Comment (bersbersbers) [reply tests/testthat/test-geom-violin.R]: I replaced the visual test by one based on the `grob`. I haven't found good documentation on how to best traverse this tree, though, but it's a start.

File: tests/testthat/test-geom-violin.R [hunk 3]
```diff
@@ -46,6 +46,48 @@ test_that("quantiles do not fail on zero-range data", {
...
 })
 
+test_that("quantiles are at expected positions", {
+  get_quantile_line <- function(y) {
+    df <- data.frame(x = 1, y = y)
+
+    p <- ggplot(df, aes(x = x, y = y)) +
+      geom_violin(draw_quantiles = c(0.5), bw = 0.1)
+
+    grob <- layer_grob(p)
```
Comment (hadley) [inline tests/testthat/test-geom-violin.R:56]: Instead of testing the grobs, could you just test `create_quantile_segment_frame()` directly?

Comment (bersbersbers) [reply tests/testthat/test-geom-violin.R]: Good idea, done. In this process, I removed the test for the non-zero middle because that is covered by "`create_quantile_segment_frame` functions for 3 quantiles".

**Review by hadley — APPROVED** [review]

**Comment by hadley** [comment]
Perfect, thanks!
