### PR TITLE
Fix ordering in plyr compats...

### LINKED ISSUE #3313: facet_wrap() and facet_grid() with a date variable is broken
The revdeps (#3303) identified that using `facet_grid()` or `facet_wrap()` with a date variable is broken. This probably affects other S3 vectors as well.

``` r
library(ggplot2)
df <- data.frame(date = as.Date("2019-01-01"), x = 1, y = 1)
p <- ggplot(df, aes(x, y)) + geom_point()
p + facet_grid(vars(date))
#> Error in scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales):
p + facet_wrap(vars(date))
#> Error in scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales):
```

The error is in `Facet(Grid|Wrap)$map_data()`, where there is a join between the layout and the panels. In one of these, `date` is a factor, and in the other, it is an S3 `Date`. This changed because of different behaviour between `join_keys()` and its previous **plyr** counterpart.

### PR DESCRIPTION
**Pull request by thomasp85**
Fixes #3313 and #3315 

This fixes the differences in ordering between plyr and the replacement functions. Some notes

- the plyr ordering in `ddply()` is based on a pretty weird heuristic but I think I've nailed it
- the difference in `join_keys()` is the result of differences in `rbind_dfs()` and `plyr::rbind.fill()`. I honestly think the current ggplot2 approach is more correct, but I've made Date handling even with plyr to unbreak revdeps... If that fixes everything we should leave it at that instead of pursuing other parity with other weird vector formats

I probably don't have a head for more work this week, so bear with me if there are any problems with the PR

### CODE REVIEW

**Comment by yutannihilation** [comment]
It seems this test fails:

https://github.com/tidyverse/ggplot2/blob/291cd7e826a2581d1fa6013d8840fe2ac31ddc76/tests/testthat/test-layer.r#L59-L64

Error:

```
names(p[[1]]) not identical to c("PANEL", "x", "group").
2/3 mismatches
x[1]: "x"
y[1]: "PANEL"

x[2]: "PANEL"
y[2]: "x"
```

This ordering was tweaked in #3013, so I guess you just need to revert this.

https://github.com/tidyverse/ggplot2/pull/3013/files#diff-12165842aeed0c5cb8c55e833132b58c

File: R/compat-plyr.R [hunk 1]
```diff
@@ -310,6 +314,7 @@ rbind_dfs <- function(dfs) {
   attributes(out) <- list(class = "data.frame", names = names(out), row.names = .set_row_names(total))
   out
 }
+date_origin <- Sys.Date() - unclass(Sys.Date())
```
Comment (clauswilke) [inline R/compat-plyr.R]: Is this the kind of global assignment that should be moved to `.onLoad()`?

Comment (thomasp85) [reply R/compat-plyr.R]: Oh, yeah. Good catch 🙂
