### PR TITLE
Fixes #3533 - Swap date(time) types in opposite scale

### LINKED ISSUE #3533: Suggestion: improve error message on wrong use of scale_x_datetime
The following code yields an error message 
```
date_issues <- tibble(dates = lubridate::ymd(c("2019-09-19", "2019-09-20", "2019-09-21")), values = 1:3)

ggplot(date_issues, aes(x = dates, y = values)) + 
   geom_line() + 
   scale_x_datetime(date_minor_breaks = "1 day")
```
The error is:
```
Error: Invalid input: time_trans works with objects of class POSIXct only
```

The reason is that we are using the wrong scale function. We should be using `scale_x_date` instead of `scale_x_datetime`. 

A "suggestion flavored" error message would help the user understand and fix the issue. E.g.:

```
Error: Invalid input: time_trans works with objects of class POSIXct only. 
   Did you consider using scale_x_date() instead of scale_x_datetime()?
```

### PR DESCRIPTION
**Pull request by laurabrianna**
In both scale_*_date and scale_*datetime, added helpful error to suggest using the other type when appropriate ( #3533 )

### CODE REVIEW

**Comment by thomasp85** [comment]
Thank you for this. On closer inspection I think that we should coerce the data into the right format rather than throw an error

File: R/scale-date.R [hunk 1]
```diff
@@ -369,6 +369,10 @@ ScaleContinuousDatetime <- ggproto("ScaleContinuousDatetime", ScaleContinuous,
         i = "The value was converted to {obj_type_friendly(x)}."
       ), call = self$call)
     }
+    if (inherits(x, "Date")) {
+     cli::cli_abort("You supplied a {.cls {class(x)}} field.
+                    Did you mean to use {.fn scale_*_date}?", call = self$call)
```
Comment (thomasp85) [inline R/scale-date.R:374]:
```suggestion
     x <- as.POSIXct(x)
```

File: R/scale-date.R [hunk 2]
```diff
@@ -416,6 +420,10 @@ ScaleContinuousDate <- ggproto("ScaleContinuousDate", ScaleContinuous,
         i = "The value was converted to {obj_type_friendly(x)}."
       ), call = self$call)
     }
+    if (inherits(x, "POSIXct")) {
+      cli::cli_abort("You supplied a {.cls {class(x)}} field.
+                    Did you mean to use {.fn scale_*_datetime}?", call = self$call)
```
Comment (thomasp85) [inline R/scale-date.R:425]:
```suggestion
      x <- as.Date(x)
```

**Review by thomasp85 — CHANGES_REQUESTED** [review]

**Review by thomasp85 — COMMENTED** [review]
@teunbrand would you look into finishing this off?

**Review by thomasp85 — APPROVED** [review]
LGTM
