### PR TITLE
Fix for `position_dodge(preserve = "single")` with location based data

### LINKED ISSUE #3647: Aligning geoms with preserve = "single": appears not to work with several factors
Hi,

I discovered issue #2712 when looking for a solution to the misalignment of boxplots with overlaid points. While the solution shown works in the example, it does not seem to generalise to cases with a greater number of factors.

Ideally it would be possible to achieve the same thing with `position_jitterdodge()`, but I guess that is beyond the scope of this issue.

```r
library(ggplot2)

ggplot(mtcars, aes(factor(am), mpg, fill = factor(carb))) + 
  geom_boxplot(position = position_dodge2(0.75, preserve = 'single')) +
  geom_point(position = position_dodge(0.75, preserve = 'total'))
```

image

### LINKED ISSUE #5995: `position_dodge` not working well with `preserve = "single"` and `geom_text` (or `geom_point`)
In CRAN version, it doesn't manage to dodge the text correctly...

``` r
library(tidyverse, quietly = TRUE)
#> Warning: package 'ggplot2' was built under R version 4.4.1
```

``` r
library(palmerpenguins, quietly = TRUE)

penguins |>
  count(species, sex) |>
  ggplot(
    aes(x = sex,
        y = n,
        fill = species,
        label = n),
  ) +
  geom_col(
    position = position_dodge(preserve = "single"),
    width = 0.75,
    alpha = 0.9,
  ) +
  geom_text(
    colour = "black",
    position = position_dodge(width = 0.75, preserve = "single"),
    vjust = 1.33,
  )
#> Warning in max(table(panel$xmin)): no non-missing arguments to max; returning
#> -Inf
```

<sup>Created on 2024-07-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

With DEV version downloaded just now, it errors
image

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #5995 and fix #3647.

Briefly, when `xmin` is absent from the data, `x` is used to count the number of groups per location.
In addition, some guardrails are in place to not use non-existing columns in the calculation.

Reprex from issue:
``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

palmerpenguins::penguins |>
  dplyr::count(species, sex) |>
  ggplot(
    aes(x = sex,
        y = n,
        fill = species,
        label = n),
  ) +
  geom_col(
    position = position_dodge(preserve = "single"),
    width = 0.75,
    alpha = 0.9,
  ) +
  geom_text(
    colour = "black",
    position = position_dodge(width = 0.75, preserve = "single"),
    vjust = 1.33,
  )
```

<sup>Created on 2024-07-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by teunbrand** [comment]
Accidentally also fixes #3647:

Note previously recommended as workaround in https://github.com/tidyverse/ggplot2/issues/2712#issuecomment-399759709 was to combine `position_dodge()` in point layer with `position_dodge2()` in boxplot layer, but this workaround is no longer necessary.


``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

dodge <- position_dodge(0.75, preserve = "single")

ggplot(mtcars, aes(factor(am), mpg, fill = factor(carb))) + 
  geom_boxplot(position = dodge) +
  geom_point(position = dodge, shape = 21)
```



<sup>Created on 2024-07-24 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

File: R/position-dodge.R [hunk 1]
```diff
@@ -117,8 +117,10 @@ PositionDodge <- ggproto("PositionDodge", Position,
     if (identical(self$preserve, "total")) {
       n <- NULL
     } else {
-      n <- vec_unique(data[c("group", "PANEL", "xmin")])
-      n <- vec_group_id(n[c("PANEL", "xmin")])
+      data$xmin <- data$xmin %||% data$x
+      cols <- intersect(colnames(data), c("group", "PANEL", "xmin"))
```
Comment (thomasp85) [inline R/position-dodge.R:121]: Since "group" and "PANEL" are required data columns and you just defined the xmin column, is there any instances where this would yield anything different than `c("group", "PANEL", "xmin")`?

Comment (thomasp85) [reply R/position-dodge.R:121]: I guess if both "xmin" and "x" are initially `NULL` - is that what is the intend?

Comment (teunbrand) [reply R/position-dodge.R:121]: The column-name intersection is just to protect against any potentially missing columns. I imagine a determined extension could avoid creating `group` and `PANEL` columns.

Comment (thomasp85) [reply R/position-dodge.R:121]: If so, it would break in a multitude of other places as both columns are assumed to exist all over the place

**Review by thomasp85 — APPROVED** [review]
Apart from the ongoing discussion where I am still not convinced this LGTM

File: R/position-dodge.R (hunk 1 above)
Comment (teunbrand) [reply R/position-dodge.R:121]: If we assume all well-behaved extensions, then still xmin/x can be `NULL` as you pointed out. But then there'd be multiple downstream assumptions that no longer hold too.

Comment (thomasp85) [reply R/position-dodge.R:121]: It is not necessary to assume well-behaved extensions. The extensions would never work in any settings if they removed these columns so they _cannot_ exist in any meaningful way. If there is a chance that min/x is NULL then this should be guarded by a proper error

Comment (teunbrand) [reply R/position-dodge.R:126]: Alright I've thrown in a `check_required_aesthetics()` in here

**Comment by teunbrand** [comment]
We can have another stab at ironing out details once #6101 is fleshed out
